from app import db

class Company(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    owner_name = db.Column(db.String(100), nullable=False)
    address = db.Column(db.String(200), nullable=False)
    owner_phone = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(120), nullable=False)
    website = db.Column(db.String(120), nullable=False)
    instagram = db.Column(db.String(120), nullable=True)
    facebook = db.Column(db.String(120), nullable=True)
    twitter = db.Column(db.String(120), nullable=True)
    opening_time = db.Column(db.String(20), nullable=False)
    closing_time = db.Column(db.String(20), nullable=False)
    ppf_price = db.Column(db.Integer, nullable=False)
    ceramic_coating_price = db.Column(db.Integer, nullable=False)
    full_detail_price = db.Column(db.Integer, nullable=False)
    interior_detail_price = db.Column(db.Integer, nullable=False)
    exterior_detail_price = db.Column(db.Integer, nullable=False)
    headlight_restoration_price = db.Column(db.Integer, nullable=False)
    windshield_repair_price = db.Column(db.Integer, nullable=False)
    odor_removal_price = db.Column(db.Integer, nullable=False)
    discount_rules = db.Column(db.Text, nullable=True)